### ISSUE TITLE
DW texts minor: Six segs too much

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/dw-data#43]
There are six segs containing F22s that are incorporated in another F22 from a title level m; but this title level m has a "Entst." in its date, so there is no published expression, ergo no segments should exist. 
```
#INT16 segment
<https://sk.acdh.oeaw.ac.at/DWbibl00425/segment> a ns1:INT16_Segment ;
  rdfs:label "Segment: An einen deutschen Fürsten"@en ;
  ns1:R16_incorporates <https://sk.acdh.oeaw.ac.at/DWbibl00425> ;
  ns1:R25_is_segment_of <https://sk.acdh.oeaw.ac.at/DWbibl04601/published-expression> .
```
Currently, there are 1832 segs, should be only 1826.

**Comment by BergListe** [comment]
Hopefully fixed this now without adding new bugs...

**Comment by BOberreither** [comment]
@BergListe Better, because the Segs are gone, but indeed there is something missing now, namely this (copied it from an older version):
```
#F22 issue
<https://sk.acdh.oeaw.ac.at/DWbibl04601> a frbroo:F22_Self-Contained_Expression ;
  rdfs:label "Polenlieder"@en ;
  cidoc:P102_has_title <https://sk.acdh.oeaw.ac.at/DWbibl04601/title/0> ;
  cidoc:P165_incorporates <https://sk.acdh.oeaw.ac.at/DWbibl00425> .

#F22 title issue
<https://sk.acdh.oeaw.ac.at/DWbibl04601/title/0> a cidoc:E35_Title ;
  cidoc:P102i_is_title_of <https://sk.acdh.oeaw.ac.at/DWbibl04601> ;
  rdfs:label "Title: Polenlieder"@en ;
  cidoc:P2_has_type <https://sk.acdh.oeaw.ac.at/types/title/main> ;
  rdf:value "Polenlieder" .
```

**Comment by BergListe** [comment]
I'm not sure if I completely understand this problem. Shouldn't there be a `<bibl xml:id="DWbibl04601"/>`? All I can find is six entries  containing titles like this: `<title level="m" key="#DWbibl04601">Polenlieder</title>`

**Comment by BOberreither** [comment]
@BergListe No, these F22s are built from title level m, and they incorporate other F22s built from their title level a's. Since there is no publication event, but only a text creation, there cannot be a published expression (F24) of these F22s, and there should not be segs - which are by definition parts of these published expressions.

**Comment by BergListe** [comment]
Done

**Comment by BOberreither** [comment]
@BergListe Hate to say it, but I still get a match under the wrong URI: https://sk.acdh.oeaw.ac.at/
https://semantickraus.acdh.oeaw.ac.at/resource/?uri=https://sk.acdh.oeaw.ac.at/
There's no metadata attached to the entity, but it is still linked to the texts it incorporates. Found the culprit, it's in the incorporated text's F22 statement, last line.
```
#F22 art-issue
<https://sk.acdh.oeaw.ac.at/DWbibl00430> a frbroo:F22_Self-Contained_Expression ;
  rdfs:label "Gesang der Polen"@en ;
  cidoc:P102_has_title <https://sk.acdh.oeaw.ac.at/DWbibl00430/title/0> ;
  cidoc:P165i_is_incorporated_in <https://sk.acdh.oeaw.ac.at/> .
```
My suggestion: Make a filter so this last line doesn't get built unless there is an ID to put there. Because we don't necessarily need the line, the relation between incorporating and incorporated F22 is already correct in the "Polenlieder"-Statement.

**Comment by BergListe** [comment]
Should we re-open this issue or is this not a problem anymore?
